#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 合并上游

on:
  push:
    branches: 
      - dev-lean-lede
  schedule:
    - cron: 30 03 */3 * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: 查看
      uses: actions/checkout@master
      with:
        ref: dev-lean-lede
        fetch-depth: 0
        lfs: true

    - name: 设置git身份
      run : |
        git config --global user.email "KFER.Mercer@gmail.com"
        git config --global user.name "KFERMercer"
    - name: Load upstream commits
      run: git pull https://github.com/Lienol/openwrt.git dev-lean-lede

    - name: 推送提交
      env:
        DOWNSTREAM_BRANCH: dev-lean-lede
      run: git push origin $DOWNSTREAM_BRANCH
